name: AfkSystem
<<<<<<< HEAD
version: 1.0.0
main: xeonch\afksystem\AfkSystem
api: 5.0.0
=======
version: 1.5.0
main: xeonch\afksystem\AfkSystem
api: 5.0.0
description: A very useful plugin for managing the afk player
>>>>>>> 894b5eb (Update 1.5.0)
src-namespace-prefix: xeonch\afksystem
author: XeonCh

permissions:
  afksystem.command.afk:
    default: true